 
   
name: Main

on:
  push:
    branches: [ master ]
    
env:
  MFE_NAME: "Vijay"
  NODE_VERSION: "14.x"
#  NPM_AUTH: ${{ secrets.EXEC_ETMS_ARTIFACTORY_AUTH }} 
  
jobs:
  release:
    name: Release ${{ github.event.inputs.type }} version
    runs-on: ubuntu-latest
   # env:
    #  RELEASE_TOKEN: ${{ secrets.EXEC_TM_ESNTL_DEPLOYMENTS_PAT }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        #  token: ${{ env.RELEASE_TOKEN }}

      - name: Set git credentials
        uses: fregante/setup-git-user@v1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: |
         # npm config set _auth="$NPM_AUTH"
          npm install
          
      - name: Check format
        run: |
          npm run prettier
      - name: Check linting
        run: |
          npm run lint
      
      - name: Build Package
        run: |
          git status
          npm run-script build
          
      - name: Tar the vijay.tar build folder, manifest.json, and env.ejs template
        run: |
          tar -cvf $MFE_NAME.tar build public/manifest.json -C .github/envs/ env.ejs
