 on:
  workflow_call:
    inputs:
      MFE_NAME:
        required: true
        type: string
jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: rajkumarvijay/mavenrepo/blob/master/.github/workflows/main.yml
        with:
          MFE_NAME: Gopi
